// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApp.Data.Context;

#nullable disable

namespace ProductApp.Data.Migrations
{
    [DbContext(typeof(ProductAppContext))]
    [Migration("20220611150040_two")]
    partial class two
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductApp.Entity.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductApp.Entity.Models.ProductSparepart", b =>
                {
                    b.Property<int>("SparepartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("SparepartID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductSpareparts");
                });

            modelBuilder.Entity("ProductApp.Entity.Models.Sparepart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SparepartCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SparepartName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SparepartPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Spareparts");
                });

            modelBuilder.Entity("ProductApp.Entity.Models.ProductSparepart", b =>
                {
                    b.HasOne("ProductApp.Entity.Models.Product", "Product")
                        .WithMany("ProductSpareparts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductApp.Entity.Models.Sparepart", "Sparepart")
                        .WithMany("ProductSpareparts")
                        .HasForeignKey("SparepartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sparepart");
                });

            modelBuilder.Entity("ProductApp.Entity.Models.Product", b =>
                {
                    b.Navigation("ProductSpareparts");
                });

            modelBuilder.Entity("ProductApp.Entity.Models.Sparepart", b =>
                {
                    b.Navigation("ProductSpareparts");
                });
#pragma warning restore 612, 618
        }
    }
}
